#!/usr/bin/env ruby

require_relative 'git_utils.rb'

def install_utilities
  `gem install bundler`
  `bundle install`
end

def configure_remote
  `git remote rm jp`
  `git remote add jp git://github.com/developwithpassion/dnrtv_dotnet_bootcamp_prep.git`
end

def create_first_branch
  checkout("start_of_week")
end

install_utilities
configure_remote
create_first_branch
`./start_new_exercise`
